metadata:
  creationTimestamp: "2025-05-14T16:50:24Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          .: {}
          k:{"uid":"30154dce-1695-472b-8dce-1f582c24acbf"}: {}
      f:spec:
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":9090,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: site-controller
    operation: Update
    time: "2025-05-14T16:50:24Z"
  name: skupper-prometheus
  namespace: silm-mongodb
  ownerReferences:
  - apiVersion: v1
    kind: ConfigMap
    name: skupper-site
    uid: 30154dce-1695-472b-8dce-1f582c24acbf
  resourceVersion: "8433023846"
  uid: 971d7afc-fc19-4bcc-b354-b54cbd1429ba
spec:
  clusterIP: 254.53.36.119
  clusterIPs:
  - 254.53.36.119
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: prometheus
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/name: skupper-prometheus
    app.kubernetes.io/part-of: skupper
    skupper.io/component: prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
