metadata:
  creationTimestamp: "2025-05-14T16:50:55Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          .: {}
          k:{"uid":"85f36ae8-19b9-49fd-833d-02e53be0ab0e"}: {}
      f:spec:
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":9090,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: site-controller
    operation: Update
    time: "2025-05-14T16:50:55Z"
  name: skupper-prometheus
  namespace: silm-mongodb
  ownerReferences:
  - apiVersion: v1
    kind: ConfigMap
    name: skupper-site
    uid: 85f36ae8-19b9-49fd-833d-02e53be0ab0e
  resourceVersion: "8685038439"
  uid: 68fe82e0-1dc6-49b8-9725-b78d082c26eb
spec:
  clusterIP: 254.52.232.171
  clusterIPs:
  - 254.52.232.171
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: prometheus
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/name: skupper-prometheus
    app.kubernetes.io/part-of: skupper
    skupper.io/component: prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
