data:
  prd-mc-rs-mdb-0-0-svc: '{"address":"prd-mc-rs-mdb-0-0-svc","protocol":"tcp","ports":[27017,27018],"exposeIngress":"","targets":[{"name":"prd-mc-rs-mdb-0-0.prd-mc-rs-mdb-0-svc","targetPorts":{"27017":27017,"27018":27018},"service":"prd-mc-rs-mdb-0-0.prd-mc-rs-mdb-0-svc"}]}'
  prd-mc-rs-mdb-0-1-svc: '{"address":"prd-mc-rs-mdb-0-1-svc","protocol":"tcp","ports":[27017,27018],"exposeIngress":"","targets":[{"name":"prd-mc-rs-mdb-0-1.prd-mc-rs-mdb-0-svc","targetPorts":{"27017":27017,"27018":27018},"service":"prd-mc-rs-mdb-0-1.prd-mc-rs-mdb-0-svc"}]}'
  prd-mc-rs-mdb-1-0-svc: '{"address":"prd-mc-rs-mdb-1-0-svc","protocol":"tcp","ports":[27017,27018],"exposeIngress":"","targets":[],"origin":"30154dce-1695-472b-8dce-1f582c24acbf"}'
metadata:
  creationTimestamp: "2025-05-14T16:50:53Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          .: {}
          k:{"uid":"85f36ae8-19b9-49fd-833d-02e53be0ab0e"}: {}
    manager: site-controller
    operation: Update
    time: "2025-05-14T16:50:53Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:prd-mc-rs-mdb-0-0-svc: {}
        f:prd-mc-rs-mdb-0-1-svc: {}
    manager: skupper.exe
    operation: Update
    time: "2025-05-14T16:52:43Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:prd-mc-rs-mdb-1-0-svc: {}
    manager: service-controller
    operation: Update
    time: "2025-06-11T03:02:57Z"
  name: skupper-services
  namespace: silm-mongodb
  ownerReferences:
  - apiVersion: v1
    kind: ConfigMap
    name: skupper-site
    uid: 85f36ae8-19b9-49fd-833d-02e53be0ab0e
  resourceVersion: "9703928641"
  uid: c5233897-4c10-4275-9371-b83e8b19d5b7
