metadata:
  annotations:
    dynakube.dynatrace.com/injected: "true"
    io.kubernetes.cri-o.TrySkipVolumeSELinuxLabel: "true"
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "254.19.20.146"
          ],
          "default": true,
          "dns": {}
      }]
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2025-07-31T14:24:10Z"
  generateName: skupper-prometheus-7696ccbd84-
  labels:
    app.kubernetes.io/name: skupper-prometheus
    app.kubernetes.io/part-of: skupper
    pod-template-hash: 7696ccbd84
    skupper.io/component: prometheus
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/part-of: {}
          f:pod-template-hash: {}
          f:skupper.io/component: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"62327b54-2ffa-437e-a9c6-31000c213c97"}: {}
      f:spec:
        f:containers:
          k:{"name":"prometheus-server"}:
            .: {}
            f:args: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/etc/prometheus"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/prometheus"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:serviceAccount: {}
        f:serviceAccountName: {}
        f:terminationGracePeriodSeconds: {}
        f:volumes:
          .: {}
          k:{"name":"prometheus-config"}:
            .: {}
            f:configMap:
              .: {}
              f:defaultMode: {}
              f:name: {}
            f:name: {}
          k:{"name":"prometheus-storage-volume"}:
            .: {}
            f:emptyDir: {}
            f:name: {}
    manager: kube-controller-manager
    operation: Update
    time: "2025-07-31T14:24:10Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:k8s.v1.cni.cncf.io/network-status: {}
    manager: multus-daemon
    operation: Update
    time: "2025-07-31T14:24:12Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"PodReadyToStartContainers"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:hostIPs: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"254.19.20.146"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2025-07-31T14:24:27Z"
  name: skupper-prometheus-7696ccbd84-2bsz5
  namespace: silm-mongodb
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: skupper-prometheus-7696ccbd84
    uid: 62327b54-2ffa-437e-a9c6-31000c213c97
  resourceVersion: "9249991720"
  uid: 29cc8b99-e06f-4d12-96c5-f957392a4474
spec:
  containers:
  - args:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus/
    - --web.config.file=/etc/prometheus/web-config.yml
    image: registry.redhat.io/openshift4/ose-prometheus@sha256:baf5189676a5dc386e41c1e2a0455db4ec3394b47a411cb604c3fa1933e270a5
    imagePullPolicy: Always
    name: prometheus-server
    resources:
      limits:
        cpu: 100m
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 128Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1002270000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/prometheus
      name: prometheus-config
    - mountPath: /prometheus
      name: prometheus-storage-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-pxlpd
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: skupper-prometheus-dockercfg-q2dg9
  nodeName: bmworker28.ocp-prd-dor.bell.corp.bce.ca
  nodeSelector:
    metal: "true"
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  runtimeClassName: selinux
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1002270000
    fsGroupChangePolicy: OnRootMismatch
    seLinuxOptions:
      level: s0:c48,c7
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: skupper-prometheus
  serviceAccountName: skupper-prometheus
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - configMap:
      defaultMode: 420
      name: prometheus-server-config
    name: prometheus-config
  - emptyDir: {}
    name: prometheus-storage-volume
  - name: kube-api-access-pxlpd
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-07-31T14:24:27Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-07-31T14:24:10Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-07-31T14:24:27Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-07-31T14:24:27Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-07-31T14:24:10Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://db90dd4640e8cb9ab7b7a31c2a4860fb6c81d05e2e101e26c0542c1775722e78
    image: registry.redhat.io/openshift4/ose-prometheus@sha256:baf5189676a5dc386e41c1e2a0455db4ec3394b47a411cb604c3fa1933e270a5
    imageID: registry.redhat.io/openshift4/ose-prometheus@sha256:044daf61b3df0592dfa8115c664410301d3ffe4bdd1d4b53cb6d9faffba8ddae
    lastState: {}
    name: prometheus-server
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-07-31T14:24:26Z"
  hostIP: 10.36.160.177
  phase: Running
  podIP: 254.19.20.146
  podIPs:
  - ip: 254.19.20.146
  qosClass: Burstable
  startTime: "2025-07-31T14:24:10Z"
